// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARW7HWLrPdO2XjpLrCQqv8B8qjxeZmcTs',
    appId: '1:511258248307:web:7f65e94781332a6a021606',
    messagingSenderId: '511258248307',
    projectId: 'notes-app-e4686',
    authDomain: 'notes-app-e4686.firebaseapp.com',
    storageBucket: 'notes-app-e4686.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY3LsvtCn4a3YIDuN1Mpv2ig4NFPSqzcI',
    appId: '1:511258248307:android:5d845d0a5db957ae021606',
    messagingSenderId: '511258248307',
    projectId: 'notes-app-e4686',
    storageBucket: 'notes-app-e4686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvRcO7qHd2v_3AmqnVz9d1X-SRuHwpY0s',
    appId: '1:511258248307:ios:2a6f064ac4b79f68021606',
    messagingSenderId: '511258248307',
    projectId: 'notes-app-e4686',
    storageBucket: 'notes-app-e4686.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvRcO7qHd2v_3AmqnVz9d1X-SRuHwpY0s',
    appId: '1:511258248307:ios:c559d978426ee012021606',
    messagingSenderId: '511258248307',
    projectId: 'notes-app-e4686',
    storageBucket: 'notes-app-e4686.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
